[
    {
        "productName": "TEBCIN",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Validamycin 5% + Tebuconazole 15% SC",
        "category": "FUNGICIDES",
        "formulation": "SC",
        "groupModeOfAction": "Contact + Systemic; FRAC 18 + 3",
        "packSize": "500 ml, 1 L, 5 L",
        "targetCrops": "Rice",
        "recommendedDosage": "400 ml/acre",
        "targetPestsDiseases": "Sheath Blight, Rice Blast",
        "productOverviewAndEfficacy": "Dual-action fungicide combining contact and systemic activity for effective management of major fungal diseases in rice."
    },
    {
        "productName": "MANGO BAR",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Paclobutrazol 23% SC",
        "category": "AT-PLANT / PLANT GROWTH REGULATOR",
        "formulation": "SC",
        "groupModeOfAction": "Plant Growth Regulator; Gibberellin Biosynthesis Inhibitor",
        "packSize": "100 ml, 200 ml, 500 ml",
        "targetCrops": "Mango",
        "recommendedDosage": "As per crop age, tree size and application method; exact brand dosage not specified",
        "targetPestsDiseases": "Excess vegetative growth, flowering management",
        "productOverviewAndEfficacy": "Paclobutrazol-based plant growth regulator that suppresses excessive vegetative growth and supports improved flowering and fruiting in mango."
    },
    {
        "productName": "MAFIA Gold",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Azotobacter + PSB (Phosphate Solubilizing Bacteria)",
        "category": "AT-PLANT / BIOFERTILIZER",
        "formulation": "SL",
        "groupModeOfAction": "Nitrogen Fixing & Phosphate Solubilizing Biofertilizer",
        "packSize": "500 g, 1 kg",
        "targetCrops": "Corn, Field Corn, Sweet Corn, Sorghum",
        "recommendedDosage": "400–800 g/acre",
        "targetPestsDiseases": "Nutrient deficiency, poor root development and low nutrient availability",
        "productOverviewAndEfficacy": "Microbial biofertilizer combining nitrogen-fixing Azotobacter and phosphate-solubilizing bacteria to improve nutrient availability, root development and plant growth."
    },
    {
        "productName": "SHIM PYROX",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Pyroxasulfone 85% WG",
        "category": "HERBICIDES",
        "formulation": "WG",
        "groupModeOfAction": "Group 15; Very Long Chain Fatty Acid (VLCFA) Synthesis Inhibitor",
        "packSize": "Not specified",
        "targetCrops": "Wheat, Maize, Soybean",
        "recommendedDosage": "As per crop and label recommendation",
        "targetPestsDiseases": "Annual grasses and broadleaf weeds",
        "productOverviewAndEfficacy": "Pre-emergence herbicide that inhibits VLCFA synthesis and provides residual control of important annual grass and broadleaf weeds."
    },
    {
        "productName": "MARKO",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Pendimethalin 30% + Imazethapyr 2% EC",
        "category": "HERBICIDES",
        "formulation": "EC",
        "groupModeOfAction": "Group 3 + Group 2; Microtubule Assembly Inhibitor + ALS/AHAS Inhibitor",
        "packSize": "Not specified",
        "targetCrops": "Soybean",
        "recommendedDosage": "2.5–3.0 L/ha",
        "targetPestsDiseases": "Echinochloa, Digera, Commelina, Amaranthus, Portulaca",
        "productOverviewAndEfficacy": "Dual-mode herbicide combining residual and ALS-inhibiting activity for broad-spectrum weed management in soybean."
    },
    {
        "productName": "MARKO 30",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Pendimethalin 30% EC",
        "category": "HERBICIDES",
        "formulation": "EC",
        "groupModeOfAction": "Group 3; Microtubule Assembly Inhibitor",
        "packSize": "500 ml",
        "targetCrops": "Soybean, Cotton, Paddy, Wheat, Groundnut, Pigeon Pea, Onion",
        "recommendedDosage": "1–1.6 L/acre",
        "targetPestsDiseases": "Annual grasses and broadleaf weeds",
        "productOverviewAndEfficacy": "Pre-emergence herbicide providing residual control of annual grasses and broadleaf weeds across several field crops."
    },
    {
        "productName": "ROMAN EXTRA",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Azoxystrobin 2.5% + Thiophanate Methyl 11.25% + Thiamethoxam 25% FS",
        "category": "INSECTICIDES & FUNGICIDES",
        "formulation": "FS",
        "groupModeOfAction": "FRAC 11 + FRAC 1 + IRAC 4A",
        "packSize": "Not specified",
        "targetCrops": "Soybean",
        "recommendedDosage": "10 ml/kg seed",
        "targetPestsDiseases": "Fusarium Root Rot, Phytophthora Root Rot, Rhizoctonia Seedling Blight, Pythium Seedling Blight, Shoot Fly, Termites, White Grub",
        "productOverviewAndEfficacy": "Seed treatment combining fungicidal and insecticidal activity to protect seeds and seedlings from soil-borne diseases and early-season insect pests."
    },
    {
        "productName": "TAMRON ULTRA",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Thiophanate Methyl 41.7% SC",
        "category": "FUNGICIDES",
        "formulation": "SC",
        "groupModeOfAction": "FRAC 1; Methyl Benzimidazole Carbamate (MBC)",
        "packSize": "500 ml",
        "targetCrops": "Paddy, Chilli, Groundnut",
        "recommendedDosage": "1000 ml/ha",
        "targetPestsDiseases": "Blast, Grain Discoloration, Anthracnose, Tikka / Leaf Spot",
        "productOverviewAndEfficacy": "Systemic fungicide providing broad-spectrum protection against several fungal diseases in rice, chilli and groundnut."
    },
    {
        "productName": "HAITOR",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Pyrithiobac Sodium 10% EC",
        "category": "HERBICIDES",
        "formulation": "EC",
        "groupModeOfAction": "Group 2; ALS/AHAS Inhibitor",
        "packSize": "Not specified",
        "targetCrops": "Cotton",
        "recommendedDosage": "625–750 ml/ha",
        "targetPestsDiseases": "Trianthema, Amaranthus, Chenopodium, Digera, Celosia",
        "productOverviewAndEfficacy": "Selective herbicide for post-emergence management of important broadleaf weeds in cotton."
    },
    {
        "productName": "SHIMDOR",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Imidacloprid 17.8% SL",
        "category": "INSECTICIDES & MITICIDES",
        "formulation": "SL",
        "groupModeOfAction": "IRAC Group 4A; Nicotinic Acetylcholine Receptor Agonist",
        "packSize": "500 ml",
        "targetCrops": "Cotton, Paddy, Chilli, Sugarcane, Mango, Sunflower, Okra, Citrus, Groundnut, Tomato, Grapes",
        "recommendedDosage": "Crop-specific dosage as per label recommendation",
        "targetPestsDiseases": "Aphids, Whitefly, Jassids, Thrips, Hoppers, Termites, Mango Hopper, Leaf Miner, Psylla, Flea Beetle",
        "productOverviewAndEfficacy": "Systemic neonicotinoid insecticide providing effective control of sucking pests and selected soil and foliar insects."
    },
    {
        "productName": "TUFAN",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Lambda-Cyhalothrin 4.9% CS",
        "category": "INSECTICIDES & MITICIDES",
        "formulation": "CS",
        "groupModeOfAction": "IRAC Group 3A; Sodium Channel Modulator",
        "packSize": "500 ml",
        "targetCrops": "Cotton, Paddy, Brinjal, Okra, Tomato, Grapes, Chilli, Soybean",
        "recommendedDosage": "Crop-specific dosage as per label recommendation",
        "targetPestsDiseases": "Bollworms, Stem Borer, Leaf Folder, Shoot & Fruit Borer, Fruit Borer, Thrips, Flea Beetle, Pod Borer, Stem Fly, Semilooper",
        "productOverviewAndEfficacy": "Fast-acting pyrethroid insecticide providing contact and stomach action against a broad range of chewing and sucking insect pests."
    },
    {
        "productName": "VOLVO",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Validamycin 3% L",
        "category": "FUNGICIDES",
        "formulation": "L",
        "groupModeOfAction": "Trehalase Inhibitor; Antibiotic/Fungistatic",
        "packSize": "500 ml",
        "targetCrops": "Rice / Paddy",
        "recommendedDosage": "Approximately 800 ml/acre",
        "targetPestsDiseases": "Sheath Blight",
        "productOverviewAndEfficacy": "Systemic-type fungicidal antibiotic used primarily for effective management of sheath blight in rice."
    },
    {
        "productName": "RIDONA",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Fipronil 15% + Chlorantraniliprole 5% SC",
        "category": "INSECTICIDES & MITICIDES",
        "formulation": "SC",
        "groupModeOfAction": "IRAC Group 2B + Group 28",
        "packSize": "500 ml",
        "targetCrops": "Rice",
        "recommendedDosage": "500 ml/ha",
        "targetPestsDiseases": "Stem Borer, Leaf Folder",
        "productOverviewAndEfficacy": "Dual-mode insecticide combining GABA-gated chloride channel and ryanodine receptor activity for effective rice pest control."
    },
    {
        "productName": "AMRIT TOP",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Azoxystrobin 18.2% + Difenoconazole 11.4% SC",
        "category": "FUNGICIDES",
        "formulation": "SC",
        "groupModeOfAction": "FRAC Group 11 + Group 3",
        "packSize": "500 ml",
        "targetCrops": "Chilli, Tomato, Paddy, Maize, Wheat, Cotton, Turmeric, Onion, Sugarcane",
        "recommendedDosage": "200 ml/acre in 200 L water",
        "targetPestsDiseases": "Anthracnose, Powdery Mildew, Early Blight, Late Blight, Blast, Sheath Blight, Leaf Spot, Grey Mildew, Rust, Downy Mildew, Purple Blotch, Red Rot, Smut, Leaf Blotch, Rhizome Rot",
        "productOverviewAndEfficacy": "Broad-spectrum systemic fungicide combining two complementary modes of action for preventive and curative disease management."
    },
    {
        "productName": "HITACHI 18",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Fipronil 18.87% W/W SC",
        "category": "INSECTICIDES & MITICIDES",
        "formulation": "SC",
        "groupModeOfAction": "IRAC Group 2B; GABA-Gated Chloride Channel Inhibitor",
        "packSize": "500 ml",
        "targetCrops": "Cotton, Chilli, Rice",
        "recommendedDosage": "Cotton: 375 ml/ha; Chilli: 250 ml/ha; Rice: 250 ml/ha",
        "targetPestsDiseases": "Thrips, Aphids, Helicoverpa, Stem Borer, Leaf Folder, Brown Planthopper",
        "productOverviewAndEfficacy": "Broad-spectrum phenylpyrazole insecticide providing contact and ingestion activity against important insect pests."
    },
    {
        "productName": "SYPKAR",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Spiromesifen 22.9% SC",
        "category": "INSECTICIDES & MITICIDES",
        "formulation": "SC",
        "groupModeOfAction": "IRAC Group 23; Lipid Biosynthesis Inhibitor",
        "packSize": "500 ml",
        "targetCrops": "Cotton, Brinjal, Chilli, Tomato, Cucumber, Okra, Tea, Apple",
        "recommendedDosage": "Crop-specific dosage as per label recommendation",
        "targetPestsDiseases": "Whitefly, Whitefly Nymphs, Red Spider Mite, Chilli Yellow Mite, European Red Mite, Cucumber Mite",
        "productOverviewAndEfficacy": "Insecticide-acaricide targeting mites and whiteflies by disrupting lipid biosynthesis, including immature stages."
    },
    {
        "productName": "FLEXA",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Thifluzamide 24% SC",
        "category": "FUNGICIDES",
        "formulation": "SC",
        "groupModeOfAction": "FRAC Group 7; SDHI",
        "packSize": "500 ml",
        "targetCrops": "Rice, Tomato, Potato",
        "recommendedDosage": "Rice: 150 ml/acre; Tomato: 200 ml/acre; Potato: 2.5 ml/10 kg tuber",
        "targetPestsDiseases": "Sheath Blight, Early Blight, Black Scurf",
        "productOverviewAndEfficacy": "SDHI fungicide providing effective disease control by inhibiting fungal succinate dehydrogenase."
    },
    {
        "productName": "AROBIC",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Azoxystrobin 20% + Thifluzamide 15% w/v SC",
        "category": "FUNGICIDES",
        "formulation": "SC",
        "groupModeOfAction": "FRAC Group 11 + Group 7",
        "packSize": "500 ml",
        "targetCrops": "Rice",
        "recommendedDosage": "500–600 ml/ha",
        "targetPestsDiseases": "Sheath Blight, Leaf Blast",
        "productOverviewAndEfficacy": "Dual-mode fungicide combining QoI and SDHI activity for broad-spectrum disease management in rice."
    },
    {
        "productName": "GLOSTER",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Azoxystrobin 11% + Tebuconazole 18.3% w/w SC",
        "category": "FUNGICIDES",
        "formulation": "SC",
        "groupModeOfAction": "FRAC Group 11 + Group 3",
        "packSize": "500 ml",
        "targetCrops": "Chilli, Rice, Onion, Apple, Wheat, Tomato, Potato, Grapes",
        "recommendedDosage": "Chilli: 600 ml/ha; Rice, Onion, Wheat, Tomato, Potato, Grapes: 750 ml/ha; Apple: 1 ml/L",
        "targetPestsDiseases": "Fruit Rot, Powdery Mildew, Die-back, Sheath Blight, Purple Blotch, Scab, Yellow Rust, Early Blight, Late Blight, Downy Mildew",
        "productOverviewAndEfficacy": "Broad-spectrum combination fungicide with systemic and protective activity against multiple fungal diseases."
    },
    {
        "productName": "AMRIT",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Azoxystrobin 23% SC",
        "category": "FUNGICIDES",
        "formulation": "SC",
        "groupModeOfAction": "FRAC Group 11; QoI Fungicide",
        "packSize": "500 ml",
        "targetCrops": "Grapes, Chilli, Mango, Tomato, Potato, Cucumber, Cumin, Pomegranate",
        "recommendedDosage": "500 ml/ha; Mango: 100 ml/100 L water",
        "targetPestsDiseases": "Downy Mildew, Powdery Mildew, Anthracnose, Fruit Rot, Early Blight, Late Blight, Leaf Spot, Fruit Spot",
        "productOverviewAndEfficacy": "Systemic QoI fungicide providing preventive and curative activity against a broad range of fungal diseases."
    },
    {
        "productName": "MENTION",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Metolachlor 50% EC",
        "category": "HERBICIDES",
        "formulation": "EC",
        "groupModeOfAction": "Group 15; VLCFA Synthesis Inhibitor",
        "packSize": "500 ml",
        "targetCrops": "Soybean",
        "recommendedDosage": "2 L/ha",
        "targetPestsDiseases": "Echinochloa colona, Eleusine, Digitaria, Dactyloctenium, Panicum, Cyperus, Amaranthus",
        "productOverviewAndEfficacy": "Pre-emergence residual herbicide providing control of annual grasses, sedges and selected broadleaf weeds in soybean."
    },
    {
        "productName": "GLUFIRE",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Glufosinate Ammonium 13.5% SL (15% w/v)",
        "category": "HERBICIDES",
        "formulation": "SL",
        "groupModeOfAction": "Group 10; Glutamine Synthetase Inhibitor",
        "packSize": "500 ml",
        "targetCrops": "Cotton, Tea",
        "recommendedDosage": "Cotton: 2.5–3 L/ha; Tea: 2.5–3.3 L/ha",
        "targetPestsDiseases": "Echinochloa, Cynodon, Cyperus, Digitaria, Dactyloctenium, Imperata, Commelina, Ageratum, Eleusine, Paspalum",
        "productOverviewAndEfficacy": "Non-selective herbicide that inhibits glutamine synthetase and provides broad-spectrum control of grasses, sedges and broadleaf weeds."
    },
    {
        "productName": "GLYMAX",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Glyphosate 41% SL (Isopropylamine Salt)",
        "category": "HERBICIDES",
        "formulation": "SL",
        "groupModeOfAction": "Group 9; EPSPS Inhibitor",
        "packSize": "500 ml",
        "targetCrops": "Tea, Non-Cropped Areas",
        "recommendedDosage": "2–3 L/ha",
        "targetPestsDiseases": "Sorghum halepense, Cynodon, Cyperus, Echinochloa, Trianthema, Ageratum, Parthenium, Amaranthus, Digitaria",
        "productOverviewAndEfficacy": "Systemic non-selective herbicide that inhibits EPSPS and controls a wide range of annual and perennial weeds."
    },
    {
        "productName": "FITLO 58",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "2,4-D Amine Salt 58% SL",
        "category": "HERBICIDES",
        "formulation": "SL",
        "groupModeOfAction": "Group 4; Synthetic Auxin",
        "packSize": "500 ml",
        "targetCrops": "Wheat, Maize, Sorghum, Potato, Sugarcane, Rice, Aquatic Weed Areas, Non-Crop Areas",
        "recommendedDosage": "Crop-specific dosage as per label recommendation",
        "targetPestsDiseases": "Chenopodium, Fumaria, Melilotus, Vicia, Convolvulus, Trianthema, Amaranthus, Cyperus, Digera, Portulaca, Commelina",
        "productOverviewAndEfficacy": "Selective systemic herbicide used primarily for broadleaf weed control through synthetic auxin activity."
    },
    {
        "productName": "CLEANR",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Paraquat Dichloride 24% SL",
        "category": "HERBICIDES",
        "formulation": "SL",
        "groupModeOfAction": "Group 22; Photosystem I Electron Diversion Inhibitor",
        "packSize": "500 ml",
        "targetCrops": "Tea, Potato, Cotton, Rubber, Coffee, Rice, Wheat, Maize, Grapes, Apple",
        "recommendedDosage": "800–2000 ml/acre depending on crop and application",
        "targetPestsDiseases": "Annual Grasses, Perennial Grasses, Broadleaf Weeds, Sedges",
        "productOverviewAndEfficacy": "Fast-acting contact herbicide causing rapid desiccation of green weed tissues and providing broad-spectrum weed control."
    },
    {
        "productName": "PENOX PLUS",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "Penoxsulam 0.97% + Butachlor 38.8% SE",
        "category": "HERBICIDES",
        "formulation": "SE",
        "groupModeOfAction": "Group 2 + Group 15; ALS Inhibitor + VLCFA Synthesis Inhibitor",
        "packSize": "500 ml",
        "targetCrops": "Transplanted Rice, Direct-Seeded Rice",
        "recommendedDosage": "2000 ml/ha",
        "targetPestsDiseases": "Echinochloa colona, Echinochloa crus-galli, Cyperus iria, Cyperus difformis, Marsilea, Alternanthera, Fimbristylis, Monochoria, Ludwigia",
        "productOverviewAndEfficacy": "Dual-mode rice herbicide providing broad-spectrum pre- and early-season control of grasses, sedges and broadleaf weeds."
    },
    {
        "productName": "SHIMANZU 11:11:8",
        "brandOverlay": "SHIMANZU",
        "chemicalComposition": "NPK 11:11:8 fortified with Zinc and Boron",
        "category": "AT-PLANT / FERTILIZERS",
        "formulation": "Suspension",
        "groupModeOfAction": "NPK + Zinc & Boron; Not Applicable as Pesticide Mode of Action",
        "packSize": "500 ml",
        "targetCrops": "Broad-spectrum field and horticultural crops",
        "recommendedDosage": "Approximately 500–750 ml/acre or 5–7 ml/L, subject to product label",
        "targetPestsDiseases": "Nutrient Deficiency, Poor Plant Growth, Micronutrient Deficiency",
        "productOverviewAndEfficacy": "Balanced NPK fertilizer fortified with zinc and boron to support plant nutrition, vegetative growth and overall crop development."
    },
    {
        "productName": "Ghiroilkona R-111",
        "brandOverlay": "SHIMANZU JAPAN",
        "chemicalComposition": "Titanium Dioxide (TiO₂), Rutile Grade",
        "category": "INDUSTRIAL CHEMICALS / PIGMENTS",
        "formulation": "Rutile Grade Pigment - Powder",
        "groupModeOfAction": "Rutile Titanium Dioxide Pigment - White Opacifying Pigment",
        "packSize": "25 Kg",
        "targetCrops": "Not Applicable",
        "recommendedDosage": "Application/formulation dependent",
        "targetPestsDiseases": "Not Applicable",
        "productOverviewAndEfficacy": "White rutile titanium dioxide pigment used to provide whiteness, brightness, opacity and hiding power in coatings, plastics, paper and printing inks."
    },
    {
        "productName": "Ghiroilkona R-555",
        "brandOverlay": "SHIMANZU JAPAN",
        "chemicalComposition": "Titanium Dioxide (TiO₂), Rutile Grade",
        "category": "INDUSTRIAL CHEMICALS / PIGMENTS",
        "formulation": "Rutile Grade Pigment - Powder",
        "groupModeOfAction": "Rutile Titanium Dioxide Pigment - White Opacifying Pigment",
        "packSize": "25 Kg",
        "targetCrops": "Not Applicable",
        "recommendedDosage": "Application/formulation dependent",
        "targetPestsDiseases": "Not Applicable",
        "productOverviewAndEfficacy": "Rutile-grade white pigment providing whiteness, brightness, opacity and light-scattering/hiding properties for industrial formulations."
    },
    {
        "productName": "Ghiroilkona R-777",
        "brandOverlay": "SHIMANZU JAPAN",
        "chemicalComposition": "Titanium Dioxide (TiO₂), Rutile Grade",
        "category": "INDUSTRIAL CHEMICALS / PIGMENTS",
        "formulation": "Rutile Grade Pigment - Powder",
        "groupModeOfAction": "Rutile Titanium Dioxide Pigment - White Opacifying Pigment",
        "packSize": "25 Kg",
        "targetCrops": "Not Applicable",
        "recommendedDosage": "Application/formulation dependent",
        "targetPestsDiseases": "Not Applicable",
        "productOverviewAndEfficacy": "Rutile TiO₂ pigment used to improve whiteness, brightness, opacity and hiding power in coatings, plastics, paper and inks."
    },
    {
        "productName": "Ghiroilkona R-999",
        "brandOverlay": "SHIMANZU JAPAN",
        "chemicalComposition": "Titanium Dioxide (TiO₂), Rutile Grade",
        "category": "INDUSTRIAL CHEMICALS / PIGMENTS",
        "formulation": "Rutile Grade Pigment - Powder",
        "groupModeOfAction": "Rutile Titanium Dioxide Pigment - White Opacifying Pigment",
        "packSize": "25 Kg",
        "targetCrops": "Not Applicable",
        "recommendedDosage": "Application/formulation dependent",
        "targetPestsDiseases": "Not Applicable",
        "productOverviewAndEfficacy": "White rutile titanium dioxide pigment intended to provide high whiteness, brightness, opacity and hiding power in industrial applications."
    }
]