-- ========================================================================
-- SHIMANZU PRODUCTS - SUPABASE SQL SCRIPT
-- Paste this entire script in Supabase SQL Editor (>_ icon) and click RUN
-- ========================================================================

-- Step 1: Ensure all required columns exist in public.products
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS brand TEXT DEFAULT 'SHIMANZU';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS "group" TEXT DEFAULT '';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS in_stock BOOLEAN DEFAULT true;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS pack_sizes TEXT[] DEFAULT ARRAY['1L']::TEXT[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS crops TEXT[] DEFAULT ARRAY['All Crops']::TEXT[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS targets TEXT DEFAULT '';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS dosage TEXT DEFAULT '';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS description TEXT DEFAULT '';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS img_src TEXT DEFAULT '';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS category_label TEXT DEFAULT '';

-- Step 2: Ensure Row Level Security (RLS) allows Read/Write
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anonymous read products" ON public.products;
CREATE POLICY "Allow anonymous read products" ON public.products FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow anonymous insert products" ON public.products;
CREATE POLICY "Allow anonymous insert products" ON public.products FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous update products" ON public.products;
CREATE POLICY "Allow anonymous update products" ON public.products FOR UPDATE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow anonymous delete products" ON public.products;
CREATE POLICY "Allow anonymous delete products" ON public.products FOR DELETE TO anon, authenticated USING (true);

-- Step 3: Insert all 31 products from data.js
INSERT INTO public.products (
    name, brand, chemical, category, category_label, formulation, "group", in_stock, pack_sizes, crops, targets, dosage, description, img_src
)
VALUES
(
    'TEBCIN',
    'SHIMANZU',
    'Validamycin 5% + Tebuconazole 15% SC',
    'fungicides',
    'FUNGICIDES',
    'SC',
    'Contact + Systemic; FRAC 18 + 3',
    true,
    ARRAY['500 ml', '1 L', '5 L']::TEXT[],
    ARRAY['Rice', 'Paddy']::TEXT[],
    'Sheath Blight, Rice Blast',
    '400 ml/acre',
    'Dual-action fungicide combining contact and systemic activity for effective management of major fungal diseases in rice.',
    'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=600&q=80'
),
(
    'MANGO BAR',
    'SHIMANZU',
    'Paclobutrazol 23% SC',
    'at-plant',
    'AT-PLANT / PLANT GROWTH REGULATOR',
    'SC',
    'Plant Growth Regulator; Gibberellin Biosynthesis Inhibitor',
    true,
    ARRAY['100 ml', '200 ml', '500 ml']::TEXT[],
    ARRAY['Mango', 'Horticultural Trees']::TEXT[],
    'Excess vegetative growth, flowering management',
    'As per crop age, tree size and application method; exact brand dosage not specified',
    'Paclobutrazol-based plant growth regulator that suppresses excessive vegetative growth and supports improved flowering and fruiting in mango.',
    'https://images.unsplash.com/photo-1622383563227-04401ab4e5ea?auto=format&fit=crop&w=600&q=80'
),
(
    'MAFIA Gold',
    'SHIMANZU',
    'Azotobacter + PSB (Phosphate Solubilizing Bacteria)',
    'at-plant',
    'AT-PLANT / BIOFERTILIZER',
    'SL',
    'Nitrogen Fixing & Phosphate Solubilizing Biofertilizer',
    true,
    ARRAY['500 g', '1 kg']::TEXT[],
    ARRAY['Corn', 'Field Corn', 'Sweet Corn', 'Sorghum']::TEXT[],
    'Nutrient deficiency, poor root development and low nutrient availability',
    '400–800 g/acre',
    'Microbial biofertilizer combining nitrogen-fixing Azotobacter and phosphate-solubilizing bacteria to improve nutrient availability, root development and plant growth.',
    'https://images.unsplash.com/photo-1622383563227-04401ab4e5ea?auto=format&fit=crop&w=600&q=80'
),
(
    'SHIM PYROX',
    'SHIMANZU',
    'Pyroxasulfone 85% WG',
    'herbicides',
    'HERBICIDES',
    'WG',
    'Group 15; Very Long Chain Fatty Acid (VLCFA) Synthesis Inhibitor',
    true,
    ARRAY['100 g', '250 g', '500 g']::TEXT[],
    ARRAY['Wheat', 'Maize', 'Soybean']::TEXT[],
    'Annual grasses and broadleaf weeds',
    'As per crop and label recommendation',
    'Pre-emergence herbicide that inhibits VLCFA synthesis and provides residual control of important annual grass and broadleaf weeds.',
    'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=600&q=80'
),
(
    'MARKO',
    'SHIMANZU',
    'Pendimethalin 30% + Imazethapyr 2% EC',
    'herbicides',
    'HERBICIDES',
    'EC',
    'Group 3 + Group 2; Microtubule Assembly Inhibitor + ALS/AHAS Inhibitor',
    true,
    ARRAY['1 L', '2.5 L', '5 L']::TEXT[],
    ARRAY['Soybean', 'Pulses']::TEXT[],
    'Echinochloa, Digera, Commelina, Amaranthus, Portulaca',
    '2.5–3.0 L/ha',
    'Dual-mode herbicide combining residual and ALS-inhibiting activity for broad-spectrum weed management in soybean.',
    'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=600&q=80'
),
(
    'MARKO 30',
    'SHIMANZU',
    'Pendimethalin 30% EC',
    'herbicides',
    'HERBICIDES',
    'EC',
    'Group 3; Microtubule Assembly Inhibitor',
    true,
    ARRAY['500 ml', '1 L', '5 L']::TEXT[],
    ARRAY['Soybean', 'Cotton', 'Paddy', 'Wheat', 'Groundnut', 'Pigeon Pea', 'Onion']::TEXT[],
    'Annual grasses and broadleaf weeds',
    '1–1.6 L/acre',
    'Pre-emergence herbicide providing residual control of annual grasses and broadleaf weeds across several field crops.',
    'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=600&q=80'
),
(
    'ROMAN EXTRA',
    'SHIMANZU',
    'Azoxystrobin 2.5% + Thiophanate Methyl 11.25% + Thiamethoxam 25% FS',
    'insecticides',
    'INSECTICIDES & FUNGICIDES',
    'FS',
    'FRAC 11 + FRAC 1 + IRAC 4A',
    true,
    ARRAY['250 ml', '500 ml', '1 L']::TEXT[],
    ARRAY['Soybean', 'Cotton', 'Groundnut']::TEXT[],
    'Fusarium Root Rot, Phytophthora Root Rot, Rhizoctonia Seedling Blight, Pythium Seedling Blight, Shoot Fly, Termites, White Grub',
    '10 ml/kg seed',
    'Seed treatment combining fungicidal and insecticidal activity to protect seeds and seedlings from soil-borne diseases and early-season insect pests.',
    'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=600&q=80'
),
(
    'TAMRON ULTRA',
    'SHIMANZU',
    'Thiophanate Methyl 41.7% SC',
    'fungicides',
    'FUNGICIDES',
    'SC',
    'FRAC 1; Methyl Benzimidazole Carbamate (MBC)',
    true,
    ARRAY['500 ml', '1 L']::TEXT[],
    ARRAY['Paddy', 'Chilli', 'Groundnut']::TEXT[],
    'Blast, Grain Discoloration, Anthracnose, Tikka / Leaf Spot',
    '1000 ml/ha',
    'Systemic fungicide providing broad-spectrum protection against several fungal diseases in rice, chilli and groundnut.',
    'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=600&q=80'
),
(
    'HAITOR',
    'SHIMANZU',
    'Pyrithiobac Sodium 10% EC',
    'herbicides',
    'HERBICIDES',
    'EC',
    'Group 2; ALS/AHAS Inhibitor',
    true,
    ARRAY['250 ml', '500 ml']::TEXT[],
    ARRAY['Cotton']::TEXT[],
    'Trianthema, Amaranthus, Chenopodium, Digera, Celosia',
    '625–750 ml/ha',
    'Selective herbicide for post-emergence management of important broadleaf weeds in cotton.',
    'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=600&q=80'
),
(
    'SHIMDOR',
    'SHIMANZU',
    'Imidacloprid 17.8% SL',
    'insecticides',
    'INSECTICIDES & MITICIDES',
    'SL',
    'IRAC Group 4A; Nicotinic Acetylcholine Receptor Agonist',
    true,
    ARRAY['100 ml', '250 ml', '500 ml', '1 L']::TEXT[],
    ARRAY['Cotton', 'Paddy', 'Chilli', 'Sugarcane', 'Mango', 'Sunflower', 'Okra', 'Citrus', 'Groundnut', 'Tomato', 'Grapes']::TEXT[],
    'Aphids, Whitefly, Jassids, Thrips, Hoppers, Termites, Mango Hopper, Leaf Miner, Psylla, Flea Beetle',
    'Crop-specific dosage as per label recommendation',
    'Systemic neonicotinoid insecticide providing effective control of sucking pests and selected soil and foliar insects.',
    'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=600&q=80'
),
(
    'TUFAN',
    'SHIMANZU',
    'Lambda-Cyhalothrin 4.9% CS',
    'insecticides',
    'INSECTICIDES & MITICIDES',
    'CS',
    'IRAC Group 3A; Sodium Channel Modulator',
    true,
    ARRAY['250 ml', '500 ml', '1 L']::TEXT[],
    ARRAY['Cotton', 'Paddy', 'Brinjal', 'Okra', 'Tomato', 'Grapes', 'Chilli', 'Soybean']::TEXT[],
    'Bollworms, Stem Borer, Leaf Folder, Shoot & Fruit Borer, Fruit Borer, Thrips, Flea Beetle, Pod Borer, Stem Fly, Semilooper',
    'Crop-specific dosage as per label recommendation',
    'Fast-acting pyrethroid insecticide providing contact and stomach action against a broad range of chewing and sucking insect pests.',
    'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=600&q=80'
),
(
    'VOLVO',
    'SHIMANZU',
    'Validamycin 3% L',
    'fungicides',
    'FUNGICIDES',
    'L',
    'Trehalase Inhibitor; Antibiotic/Fungistatic',
    true,
    ARRAY['500 ml', '1 L', '2 L']::TEXT[],
    ARRAY['Rice / Paddy']::TEXT[],
    'Sheath Blight',
    'Approximately 800 ml/acre',
    'Systemic-type fungicidal antibiotic used primarily for effective management of sheath blight in rice.',
    'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=600&q=80'
),
(
    'RIDONA',
    'SHIMANZU',
    'Fipronil 15% + Chlorantraniliprole 5% SC',
    'insecticides',
    'INSECTICIDES & MITICIDES',
    'SC',
    'IRAC Group 2B + Group 28',
    true,
    ARRAY['250 ml', '500 ml', '1 L']::TEXT[],
    ARRAY['Rice', 'Paddy']::TEXT[],
    'Stem Borer, Leaf Folder',
    '500 ml/ha',
    'Dual-mode insecticide combining GABA-gated chloride channel and ryanodine receptor activity for effective rice pest control.',
    'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=600&q=80'
),
(
    'AMRIT TOP',
    'SHIMANZU',
    'Azoxystrobin 18.2% + Difenoconazole 11.4% SC',
    'fungicides',
    'FUNGICIDES',
    'SC',
    'FRAC Group 11 + Group 3',
    true,
    ARRAY['200 ml', '500 ml', '1 L']::TEXT[],
    ARRAY['Chilli', 'Tomato', 'Paddy', 'Maize', 'Wheat', 'Cotton', 'Turmeric', 'Onion', 'Sugarcane']::TEXT[],
    'Anthracnose, Powdery Mildew, Early Blight, Late Blight, Blast, Sheath Blight, Leaf Spot, Grey Mildew, Rust, Downy Mildew, Purple Blotch, Red Rot, Smut, Leaf Blotch, Rhizome Rot',
    '200 ml/acre in 200 L water',
    'Broad-spectrum systemic fungicide combining two complementary modes of action for preventive and curative disease management.',
    'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=600&q=80'
),
(
    'HITACHI 18',
    'SHIMANZU',
    'Fipronil 18.87% W/W SC',
    'insecticides',
    'INSECTICIDES & MITICIDES',
    'SC',
    'IRAC Group 2B; GABA-Gated Chloride Channel Inhibitor',
    true,
    ARRAY['250 ml', '500 ml', '1 L']::TEXT[],
    ARRAY['Cotton', 'Chilli', 'Rice']::TEXT[],
    'Thrips, Aphids, Helicoverpa, Stem Borer, Leaf Folder, Brown Planthopper',
    'Cotton: 375 ml/ha; Chilli: 250 ml/ha; Rice: 250 ml/ha',
    'Broad-spectrum phenylpyrazole insecticide providing contact and ingestion activity against important insect pests.',
    'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=600&q=80'
),
(
    'SYPKAR',
    'SHIMANZU',
    'Spiromesifen 22.9% SC',
    'insecticides',
    'INSECTICIDES & MITICIDES',
    'SC',
    'IRAC Group 23; Lipid Biosynthesis Inhibitor',
    true,
    ARRAY['200 ml', '500 ml', '1 L']::TEXT[],
    ARRAY['Cotton', 'Brinjal', 'Chilli', 'Tomato', 'Cucumber', 'Okra', 'Tea', 'Apple']::TEXT[],
    'Whitefly, Whitefly Nymphs, Red Spider Mite, Chilli Yellow Mite, European Red Mite, Cucumber Mite',
    'Crop-specific dosage as per label recommendation',
    'Insecticide-acaricide targeting mites and whiteflies by disrupting lipid biosynthesis, including immature stages.',
    'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=600&q=80'
),
(
    'FLEXA',
    'SHIMANZU',
    'Thifluzamide 24% SC',
    'fungicides',
    'FUNGICIDES',
    'SC',
    'FRAC Group 7; SDHI',
    true,
    ARRAY['150 ml', '500 ml', '1 L']::TEXT[],
    ARRAY['Rice', 'Tomato', 'Potato']::TEXT[],
    'Sheath Blight, Early Blight, Black Scurf',
    'Rice: 150 ml/acre; Tomato: 200 ml/acre; Potato: 2.5 ml/10 kg tuber',
    'SDHI fungicide providing effective disease control by inhibiting fungal succinate dehydrogenase.',
    'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=600&q=80'
),
(
    'AROBIC',
    'SHIMANZU',
    'Azoxystrobin 20% + Thifluzamide 15% w/v SC',
    'fungicides',
    'FUNGICIDES',
    'SC',
    'FRAC Group 11 + Group 7',
    true,
    ARRAY['250 ml', '500 ml', '1 L']::TEXT[],
    ARRAY['Rice', 'Paddy']::TEXT[],
    'Sheath Blight, Leaf Blast',
    '500–600 ml/ha',
    'Dual-mode fungicide combining QoI and SDHI activity for broad-spectrum disease management in rice.',
    'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=600&q=80'
),
(
    'GLOSTER',
    'SHIMANZU',
    'Azoxystrobin 11% + Tebuconazole 18.3% w/w SC',
    'fungicides',
    'FUNGICIDES',
    'SC',
    'FRAC Group 11 + Group 3',
    true,
    ARRAY['250 ml', '500 ml', '1 L']::TEXT[],
    ARRAY['Chilli', 'Rice', 'Onion', 'Apple', 'Wheat', 'Tomato', 'Potato', 'Grapes']::TEXT[],
    'Fruit Rot, Powdery Mildew, Die-back, Sheath Blight, Purple Blotch, Scab, Yellow Rust, Early Blight, Late Blight, Downy Mildew',
    'Chilli: 600 ml/ha; Rice, Onion, Wheat, Tomato, Potato, Grapes: 750 ml/ha; Apple: 1 ml/L',
    'Broad-spectrum combination fungicide with systemic and protective activity against multiple fungal diseases.',
    'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=600&q=80'
),
(
    'AMRIT',
    'SHIMANZU',
    'Azoxystrobin 23% SC',
    'fungicides',
    'FUNGICIDES',
    'SC',
    'FRAC Group 11; QoI Fungicide',
    true,
    ARRAY['250 ml', '500 ml', '1 L']::TEXT[],
    ARRAY['Grapes', 'Chilli', 'Mango', 'Tomato', 'Potato', 'Cucumber', 'Cumin', 'Pomegranate']::TEXT[],
    'Downy Mildew, Powdery Mildew, Anthracnose, Fruit Rot, Early Blight, Late Blight, Leaf Spot, Fruit Spot',
    '500 ml/ha; Mango: 100 ml/100 L water',
    'Systemic QoI fungicide providing preventive and curative activity against a broad range of fungal diseases.',
    'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=600&q=80'
),
(
    'MENTION',
    'SHIMANZU',
    'Metolachlor 50% EC',
    'herbicides',
    'HERBICIDES',
    'EC',
    'Group 15; VLCFA Synthesis Inhibitor',
    true,
    ARRAY['500 ml', '1 L', '5 L']::TEXT[],
    ARRAY['Soybean', 'Pulses']::TEXT[],
    'Echinochloa colona, Eleusine, Digitaria, Dactyloctenium, Panicum, Cyperus, Amaranthus',
    '2 L/ha',
    'Pre-emergence residual herbicide providing control of annual grasses, sedges and selected broadleaf weeds in soybean.',
    'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=600&q=80'
),
(
    'GLUFIRE',
    'SHIMANZU',
    'Glufosinate Ammonium 13.5% SL (15% w/v)',
    'herbicides',
    'HERBICIDES',
    'SL',
    'Group 10; Glutamine Synthetase Inhibitor',
    true,
    ARRAY['500 ml', '1 L', '5 L']::TEXT[],
    ARRAY['Cotton', 'Tea']::TEXT[],
    'Echinochloa, Cynodon, Cyperus, Digitaria, Dactyloctenium, Imperata, Commelina, Ageratum, Eleusine, Paspalum',
    'Cotton: 2.5–3 L/ha; Tea: 2.5–3.3 L/ha',
    'Non-selective herbicide that inhibits glutamine synthetase and provides broad-spectrum control of grasses, sedges and broadleaf weeds.',
    'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=600&q=80'
),
(
    'GLYMAX',
    'SHIMANZU',
    'Glyphosate 41% SL (Isopropylamine Salt)',
    'herbicides',
    'HERBICIDES',
    'SL',
    'Group 9; EPSPS Inhibitor',
    true,
    ARRAY['500 ml', '1 L', '5 L']::TEXT[],
    ARRAY['Tea', 'Non-Cropped Areas']::TEXT[],
    'Sorghum halepense, Cynodon, Cyperus, Echinochloa, Trianthema, Ageratum, Parthenium, Amaranthus, Digitaria',
    '2–3 L/ha',
    'Systemic non-selective herbicide that inhibits EPSPS and controls a wide range of annual and perennial weeds.',
    'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=600&q=80'
),
(
    'FITLO 58',
    'SHIMANZU',
    '2,4-D Amine Salt 58% SL',
    'herbicides',
    'HERBICIDES',
    'SL',
    'Group 4; Synthetic Auxin',
    true,
    ARRAY['500 ml', '1 L', '5 L']::TEXT[],
    ARRAY['Wheat', 'Maize', 'Sorghum', 'Potato', 'Sugarcane', 'Rice', 'Aquatic Weed Areas', 'Non-Crop Areas']::TEXT[],
    'Chenopodium, Fumaria, Melilotus, Vicia, Convolvulus, Trianthema, Amaranthus, Cyperus, Digera, Portulaca, Commelina',
    'Crop-specific dosage as per label recommendation',
    'Selective systemic herbicide used primarily for broadleaf weed control through synthetic auxin activity.',
    'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=600&q=80'
),
(
    'CLEANR',
    'SHIMANZU',
    'Paraquat Dichloride 24% SL',
    'herbicides',
    'HERBICIDES',
    'SL',
    'Group 22; Photosystem I Electron Diversion Inhibitor',
    true,
    ARRAY['500 ml', '1 L', '5 L']::TEXT[],
    ARRAY['Tea', 'Potato', 'Cotton', 'Rubber', 'Coffee', 'Rice', 'Wheat', 'Maize', 'Grapes', 'Apple']::TEXT[],
    'Annual Grasses, Perennial Grasses, Broadleaf Weeds, Sedges',
    '800–2000 ml/acre depending on crop and application',
    'Fast-acting contact herbicide causing rapid desiccation of green weed tissues and providing broad-spectrum weed control.',
    'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=600&q=80'
),
(
    'PENOX PLUS',
    'SHIMANZU',
    'Penoxsulam 0.97% + Butachlor 38.8% SE',
    'herbicides',
    'HERBICIDES',
    'SE',
    'Group 2 + Group 15; ALS Inhibitor + VLCFA Synthesis Inhibitor',
    true,
    ARRAY['500 ml', '1 L', '2.5 L']::TEXT[],
    ARRAY['Transplanted Rice', 'Direct-Seeded Rice']::TEXT[],
    'Echinochloa colona, Echinochloa crus-galli, Cyperus iria, Cyperus difformis, Marsilea, Alternanthera, Fimbristylis, Monochoria, Ludwigia',
    '2000 ml/ha',
    'Dual-mode rice herbicide providing broad-spectrum pre- and early-season control of grasses, sedges and broadleaf weeds.',
    'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=600&q=80'
),
(
    'SHIMANZU 11:11:8',
    'SHIMANZU',
    'NPK 11:11:8 fortified with Zinc and Boron',
    'at-plant',
    'AT-PLANT / FERTILIZERS',
    'Suspension',
    'NPK + Zinc & Boron Fertilizer',
    true,
    ARRAY['500 ml', '1 L', '5 L']::TEXT[],
    ARRAY['Field Crops', 'Horticultural Crops', 'Vegetables', 'Fruits']::TEXT[],
    'Nutrient Deficiency, Poor Plant Growth, Micronutrient Deficiency',
    'Approximately 500–750 ml/acre or 5–7 ml/L, subject to product label',
    'Balanced NPK fertilizer fortified with zinc and boron to support plant nutrition, vegetative growth and overall crop development.',
    'https://images.unsplash.com/photo-1622383563227-04401ab4e5ea?auto=format&fit=crop&w=600&q=80'
),
(
    'Ghiroilkona R-111',
    'SHIMANZU JAPAN',
    'Titanium Dioxide (TiO₂), Rutile Grade',
    'chemicals',
    'INDUSTRIAL CHEMICALS / PIGMENTS',
    'PW',
    'Rutile Titanium Dioxide Pigment - White Opacifying Pigment',
    true,
    ARRAY['25 Kg', '500 Kg Jumbo']::TEXT[],
    ARRAY['Coatings', 'Plastics', 'Paper', 'Printing Inks']::TEXT[],
    'Whiteness, Brightness, Opacity, Hiding Power',
    'Application/formulation dependent',
    'White rutile titanium dioxide pigment used to provide whiteness, brightness, opacity and hiding power in coatings, plastics, paper and printing inks.',
    'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=600&q=80'
),
(
    'Ghiroilkona R-555',
    'SHIMANZU JAPAN',
    'Titanium Dioxide (TiO₂), Rutile Grade',
    'chemicals',
    'INDUSTRIAL CHEMICALS / PIGMENTS',
    'PW',
    'Rutile Titanium Dioxide Pigment - White Opacifying Pigment',
    true,
    ARRAY['25 Kg', '500 Kg Jumbo']::TEXT[],
    ARRAY['Industrial Formulations', 'Plastics', 'Paints', 'Masterbatch']::TEXT[],
    'Whiteness, Brightness, Opacity, Light-scattering',
    'Application/formulation dependent',
    'Rutile-grade white pigment providing whiteness, brightness, opacity and light-scattering/hiding properties for industrial formulations.',
    'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=600&q=80'
),
(
    'Ghiroilkona R-777',
    'SHIMANZU JAPAN',
    'Titanium Dioxide (TiO₂), Rutile Grade',
    'chemicals',
    'INDUSTRIAL CHEMICALS / PIGMENTS',
    'PW',
    'Rutile Titanium Dioxide Pigment - White Opacifying Pigment',
    true,
    ARRAY['25 Kg', '500 Kg Jumbo']::TEXT[],
    ARRAY['Coatings', 'Plastics', 'Paper', 'Inks', 'Masterbatch']::TEXT[],
    'High weather resistance, maximum opacity, chemical stability, UV shielding',
    'Application/formulation dependent',
    'Rutile TiO₂ pigment used to improve whiteness, brightness, opacity and hiding power in coatings, plastics, paper and inks.',
    'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=600&q=80'
),
(
    'Ghiroilkona R-999',
    'SHIMANZU JAPAN',
    'Titanium Dioxide (TiO₂), Rutile Grade',
    'chemicals',
    'INDUSTRIAL CHEMICALS / PIGMENTS',
    'PW',
    'Rutile Titanium Dioxide Pigment - White Opacifying Pigment',
    true,
    ARRAY['25 Kg', '500 Kg Jumbo']::TEXT[],
    ARRAY['Industrial Applications', 'Coatings', 'Engineering Plastics']::TEXT[],
    'High whiteness, brightness, opacity and hiding power',
    'Application/formulation dependent',
    'White rutile titanium dioxide pigment intended to provide high whiteness, brightness, opacity and hiding power in industrial applications.',
    'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=600&q=80'
);
